#!/bin/bash
# Orders Management System - Quick Start Guide
# 
# This script outlines the steps to activate the Orders Management system
# Run this manually as reference - these are setup instructions, not executable

echo "=== Orders Management System - Setup Steps ==="
echo ""
echo "STEP 1: Run Database Migration"
echo "---"
echo "Go to your Supabase dashboard:"
echo "1. Click 'SQL Editor' in the left sidebar"
echo "2. Click 'New query'"
echo "3. Copy & paste the contents of: supabase/migrations/001_orders_management.sql"
echo "4. Click 'Run'"
echo ""
echo "STEP 2: Verify Orders Table"
echo "---"
echo "Still in SQL Editor, run:"
echo "  SELECT * FROM orders LIMIT 1;"
echo ""
echo "You should see the table structure (might be empty)."
echo ""
echo "STEP 3: Environment Variables"
echo "---"
echo "Verify these are set in your .env file:"
echo "  VITE_SUPABASE_URL"
echo "  VITE_SUPABASE_ANON_KEY"
echo "  STRIPE_SECRET"
echo "  SUPABASE_URL"
echo "  SUPABASE_SERVICE_KEY"
echo ""
echo "STEP 4: Test the System"
echo "---"
echo "1. Start your dev server: npm.cmd run dev"
echo "2. Go to http://localhost:5173/checkout"
echo "3. Add a product to cart if needed"
echo "4. Complete checkout with test Stripe card: 4242 4242 4242 4242"
echo "5. After payment, verify order appears in success page"
echo "6. Go to http://localhost:5173/admin/orders"
echo "7. Your new order should appear in the table"
echo ""
echo "STEP 5: Test Admin Features"
echo "---"
echo "1. Click on an order row to open details"
echo "2. Change the status from 'pending' to 'processing'"
echo "3. Verify status updates and table refreshes"
echo "4. Test search by order number or customer name"
echo "5. Test status filter dropdown"
echo ""
echo "=== Files Created/Modified ==="
echo ""
echo "NEW FILES:"
echo "  ✓ src/lib/admin-orders.ts              - Orders library with queries"
echo "  ✓ src/routes/admin.orders.tsx          - Admin orders page"
echo "  ✓ src/routes/api/update-order-status.ts - Status update API"
echo "  ✓ src/components/site/OrderDetailsModal.tsx - Order details modal"
echo "  ✓ supabase/migrations/001_orders_management.sql - Database migration"
echo "  ✓ src/docs/orders-management.md        - Full documentation"
echo ""
echo "MODIFIED FILES:"
echo "  ✓ src/routes/api/complete-checkout-session.ts - Added order_number & status"
echo "  ✓ src/routes/admin.tsx                - Added Orders link to dashboard"
echo ""
echo "=== Architecture Overview ==="
echo ""
echo "Customer Flow:"
echo "  Checkout → Stripe Payment → Success Page → complete-checkout-session API → Supabase"
echo ""
echo "Admin Flow:"
echo "  Admin Dashboard → /admin/orders → Fetch Orders → Table Display"
echo "  Click Order → OrderDetailsModal → View Details → Update Status → API → Supabase"
echo ""
echo "=== Key Features ==="
echo ""
echo "✓ Automatic order creation with unique order numbers"
echo "✓ Complete order data (products, prices, quantities, addresses)"
echo "✓ Searchable and filterable orders table"
echo "✓ Sortable columns (date, customer, amount, status)"
echo "✓ Order details modal with full information"
echo "✓ Status management (pending → processing → shipped → delivered)"
echo "✓ Real-time updates with automatic refresh"
echo "✓ Error handling and loading states"
echo "✓ Full Supabase integration with no mock data"
echo ""
echo "=== Troubleshooting ==="
echo ""
echo "Orders not appearing?"
echo "  → Check Supabase SQL: SELECT * FROM orders;"
echo "  → Check browser console for errors"
echo "  → Verify SUPABASE_SERVICE_KEY is set"
echo ""
echo "Status updates not working?"
echo "  → Check Supabase logs for errors"
echo "  → Verify POST to /api/update-order-status succeeds"
echo "  → Check browser network tab"
echo ""
echo "For more details, see: src/docs/orders-management.md"
echo ""
