name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
      - name: Install dependencies
        run: npm ci --include=dev
      - name: Build
        run: npm run build
      - name: Run LHCI
        continue-on-error: true
        run: npm run ci:lhci
